extends Node
## Database autoload - contains all game data definitions

# ============================================================
# CHARACTER DATA
# ============================================================
var characters := {
	"maphy": {
		"name": "玛菲",
		"name_en": "Maphy",
		"description": "标准型角色，平衡的属性",
		"sprite": "res://assets/images/characters/player_maphy.png",
		"max_hp": 100,
		"speed": 200.0,
		"armor": 0,
		"damage_mult": 1.0,
		"cooldown_mult": 1.0,
		"crit_chance": 0.05,
		"crit_damage": 1.5,
		"luck": 1.0,
		"growth": 1.0,
		"greed": 1.0,
		"magnet_range": 50.0,
		"starting_weapon": "pistol",
		"passive": "",
		"color": Color(1.0, 0.4, 0.6),
		"cost": 0,
	},
	"minami": {
		"name": "美波",
		"name_en": "Minami",
		"description": "高速型角色，移动速度快",
		"sprite": "res://assets/images/characters/player_minami.png",
		"max_hp": 80,
		"speed": 260.0,
		"armor": 0,
		"damage_mult": 0.9,
		"cooldown_mult": 1.0,
		"crit_chance": 0.05,
		"crit_damage": 1.5,
		"luck": 1.0,
		"growth": 1.0,
		"greed": 1.0,
		"magnet_range": 50.0,
		"starting_weapon": "dagger",
		"passive": "movespeed",
		"color": Color(0.2, 0.4, 1.0),
		"cost": 0,
	},
	"yuria": {
		"name": "尤利娅",
		"name_en": "Yuria",
		"description": "重装型角色，高护甲高血量",
		"sprite": "res://assets/images/characters/player_yuria.png",
		"max_hp": 150,
		"speed": 170.0,
		"armor": 3,
		"damage_mult": 1.1,
		"cooldown_mult": 1.1,
		"crit_chance": 0.03,
		"crit_damage": 1.5,
		"luck": 1.0,
		"growth": 0.9,
		"greed": 1.0,
		"magnet_range": 40.0,
		"starting_weapon": "axe",
		"passive": "armor",
		"color": Color(1.0, 0.85, 0.2),
		"cost": 0,
	},
	"sakura": {
		"name": "樱",
		"name_en": "Sakura",
		"description": "攻击型角色，高伤害",
		"sprite": "res://assets/images/characters/player_sakura.png",
		"max_hp": 90,
		"speed": 200.0,
		"armor": 0,
		"damage_mult": 1.4,
		"cooldown_mult": 1.0,
		"crit_chance": 0.1,
		"crit_damage": 2.0,
		"luck": 1.0,
		"growth": 1.0,
		"greed": 1.0,
		"magnet_range": 50.0,
		"starting_weapon": "sniper",
		"passive": "damage",
		"color": Color(1.0, 0.15, 0.15),
		"cost": 0,
		"unlock_condition": "通关「公路」后解锁",
	},
	"kanna": {
		"name": "栞那",
		"name_en": "Kanna",
		"description": "魔法型角色，冷却时间短",
		"sprite": "res://assets/images/characters/player_kanna.png",
		"max_hp": 85,
		"speed": 210.0,
		"armor": 0,
		"damage_mult": 1.0,
		"cooldown_mult": 0.8,
		"crit_chance": 0.05,
		"crit_damage": 1.5,
		"luck": 1.2,
		"growth": 1.1,
		"greed": 1.0,
		"magnet_range": 60.0,
		"starting_weapon": "talisman",
		"passive": "cooldown",
		"color": Color(0.6, 0.2, 0.9),
		"cost": 500,
	},
	"kiko": {
		"name": "绮子",
		"name_en": "Kiko",
		"description": "幸运型角色，高幸运值",
		"sprite": "res://assets/images/characters/player_kiko.png",
		"max_hp": 90,
		"speed": 200.0,
		"armor": 0,
		"damage_mult": 1.0,
		"cooldown_mult": 1.0,
		"crit_chance": 0.08,
		"crit_damage": 1.8,
		"luck": 1.5,
		"growth": 1.0,
		"greed": 1.3,
		"magnet_range": 50.0,
		"starting_weapon": "baseball",
		"passive": "luck",
		"color": Color(0.2, 0.9, 0.8),
		"cost": 800,
	},
	"kureha": {
		"name": "暮叶",
		"name_en": "Kureha",
		"description": "恢复型角色，生命恢复快",
		"sprite": "res://assets/images/characters/player_kureha.png",
		"max_hp": 110,
		"speed": 200.0,
		"armor": 1,
		"damage_mult": 1.0,
		"cooldown_mult": 1.0,
		"crit_chance": 0.05,
		"crit_damage": 1.5,
		"luck": 1.0,
		"growth": 1.0,
		"greed": 1.0,
		"magnet_range": 50.0,
		"starting_weapon": "holywater",
		"passive": "recovery",
		"color": Color(0.2, 0.85, 0.3),
		"cost": 1000,
	},
	"miho": {
		"name": "美穗",
		"name_en": "Miho",
		"description": "成长型角色，经验获取多",
		"sprite": "res://assets/images/characters/player_miho.png",
		"max_hp": 95,
		"speed": 200.0,
		"armor": 0,
		"damage_mult": 1.0,
		"cooldown_mult": 1.0,
		"crit_chance": 0.05,
		"crit_damage": 1.5,
		"luck": 1.0,
		"growth": 1.5,
		"greed": 1.0,
		"magnet_range": 50.0,
		"starting_weapon": "grenade",
		"passive": "growth",
		"color": Color(1.0, 0.55, 0.1),
		"cost": 1500,
	},
	"mika": {
		"name": "米卡",
		"name_en": "Mika",
		"description": "全属性均衡偏高的高级角色",
		"sprite": "res://assets/images/characters/player_mika.png",
		"max_hp": 120,
		"speed": 230.0,
		"armor": 2,
		"damage_mult": 1.3,
		"cooldown_mult": 0.85,
		"crit_chance": 0.12,
		"crit_damage": 2.0,
		"luck": 1.3,
		"growth": 1.2,
		"greed": 1.2,
		"magnet_range": 70.0,
		"starting_weapon": "star",
		"passive": "critical",
		"color": Color(1.0, 0.3, 1.0),
		"cost": 2000,
	},
}

# ============================================================
# WEAPON DATA
# ============================================================
var weapons := {
	"pistol": {
		"name": "手枪",
		"description": "基础射击武器",
		"icon": "res://assets/images/weapons/bullet_pistol.png",
		"projectile_scene": "bullet",
		"base_damage": 10,
		"cooldown": 0.8,
		"projectile_speed": 500.0,
		"projectile_count": 1,
		"projectile_pierce": 0,
		"area_size": 1.0,
		"duration": 0.0,
		"knockback": 50.0,
		"max_level": 8,
		"evolution": "",
		"levels": [
			{"damage": 10, "count": 1, "pierce": 0, "cooldown": 0.8, "area": 1.0},
			{"damage": 12, "count": 1, "pierce": 0, "cooldown": 0.8, "area": 1.0},
			{"damage": 14, "count": 2, "pierce": 0, "cooldown": 0.7, "area": 1.0},
			{"damage": 16, "count": 2, "pierce": 1, "cooldown": 0.7, "area": 1.1},
			{"damage": 18, "count": 3, "pierce": 1, "cooldown": 0.6, "area": 1.1},
			{"damage": 20, "count": 3, "pierce": 2, "cooldown": 0.6, "area": 1.2},
			{"damage": 22, "count": 4, "pierce": 2, "cooldown": 0.5, "area": 1.2},
			{"damage": 25, "count": 4, "pierce": 3, "cooldown": 0.5, "area": 1.3},
		],
	},
	"sniper": {
		"name": "狙击步枪",
		"description": "高伤害远程武器，无限穿透",
		"icon": "res://assets/images/weapons/bullet_sniper.png",
		"projectile_scene": "bullet",
		"base_damage": 30,
		"cooldown": 2.0,
		"projectile_speed": 800.0,
		"projectile_count": 1,
		"projectile_pierce": 999,
		"area_size": 1.0,
		"duration": 0.0,
		"knockback": 100.0,
		"max_level": 8,
		"levels": [
			{"damage": 30, "count": 1, "pierce": 999, "cooldown": 2.0, "area": 1.0},
			{"damage": 38, "count": 1, "pierce": 999, "cooldown": 1.9, "area": 1.0},
			{"damage": 46, "count": 1, "pierce": 999, "cooldown": 1.8, "area": 1.1},
			{"damage": 54, "count": 2, "pierce": 999, "cooldown": 1.7, "area": 1.1},
			{"damage": 62, "count": 2, "pierce": 999, "cooldown": 1.6, "area": 1.2},
			{"damage": 70, "count": 2, "pierce": 999, "cooldown": 1.5, "area": 1.2},
			{"damage": 80, "count": 3, "pierce": 999, "cooldown": 1.4, "area": 1.3},
			{"damage": 100, "count": 3, "pierce": 999, "cooldown": 1.2, "area": 1.5},
		],
	},
	"axe": {
		"name": "消防斧",
		"description": "旋转飞斧",
		"icon": "res://assets/images/weapons/axe.png",
		"projectile_scene": "orbiting",
		"base_damage": 20,
		"cooldown": 1.5,
		"projectile_speed": 200.0,
		"projectile_count": 1,
		"projectile_pierce": 999,
		"area_size": 1.0,
		"duration": 3.0,
		"knockback": 80.0,
		"max_level": 8,
		"levels": [
			{"damage": 20, "count": 1, "pierce": 999, "cooldown": 1.5, "area": 1.0},
			{"damage": 25, "count": 2, "pierce": 999, "cooldown": 1.5, "area": 1.0},
			{"damage": 30, "count": 2, "pierce": 999, "cooldown": 1.4, "area": 1.1},
			{"damage": 35, "count": 3, "pierce": 999, "cooldown": 1.4, "area": 1.1},
			{"damage": 40, "count": 3, "pierce": 999, "cooldown": 1.3, "area": 1.2},
			{"damage": 45, "count": 4, "pierce": 999, "cooldown": 1.3, "area": 1.2},
			{"damage": 50, "count": 4, "pierce": 999, "cooldown": 1.2, "area": 1.3},
			{"damage": 60, "count": 5, "pierce": 999, "cooldown": 1.0, "area": 1.5},
		],
	},
	"grenade": {
		"name": "手榴弹",
		"description": "爆炸范围伤害",
		"icon": "res://assets/images/weapons/grenade.png",
		"projectile_scene": "explosive",
		"base_damage": 25,
		"cooldown": 2.5,
		"projectile_speed": 300.0,
		"projectile_count": 1,
		"projectile_pierce": 0,
		"area_size": 1.5,
		"duration": 0.0,
		"knockback": 150.0,
		"max_level": 8,
		"levels": [
			{"damage": 25, "count": 1, "pierce": 0, "cooldown": 2.5, "area": 1.5},
			{"damage": 32, "count": 1, "pierce": 0, "cooldown": 2.3, "area": 1.7},
			{"damage": 39, "count": 2, "pierce": 0, "cooldown": 2.1, "area": 1.9},
			{"damage": 46, "count": 2, "pierce": 0, "cooldown": 1.9, "area": 2.1},
			{"damage": 53, "count": 2, "pierce": 0, "cooldown": 1.7, "area": 2.3},
			{"damage": 60, "count": 3, "pierce": 0, "cooldown": 1.5, "area": 2.5},
			{"damage": 70, "count": 3, "pierce": 0, "cooldown": 1.3, "area": 2.7},
			{"damage": 85, "count": 4, "pierce": 0, "cooldown": 1.0, "area": 3.0},
		],
	},
	"baseball": {
		"name": "棒球",
		"description": "弹跳球体",
		"icon": "res://assets/images/weapons/baseball.png",
		"projectile_scene": "bouncing",
		"base_damage": 12,
		"cooldown": 1.2,
		"projectile_speed": 350.0,
		"projectile_count": 1,
		"projectile_pierce": 3,
		"area_size": 1.0,
		"duration": 0.0,
		"knockback": 60.0,
		"max_level": 8,
		"levels": [
			{"damage": 12, "count": 1, "pierce": 3, "cooldown": 1.2, "area": 1.0},
			{"damage": 15, "count": 1, "pierce": 4, "cooldown": 1.1, "area": 1.0},
			{"damage": 18, "count": 2, "pierce": 4, "cooldown": 1.1, "area": 1.1},
			{"damage": 21, "count": 2, "pierce": 5, "cooldown": 1.0, "area": 1.1},
			{"damage": 24, "count": 3, "pierce": 5, "cooldown": 1.0, "area": 1.2},
			{"damage": 27, "count": 3, "pierce": 6, "cooldown": 0.9, "area": 1.2},
			{"damage": 30, "count": 4, "pierce": 7, "cooldown": 0.9, "area": 1.3},
			{"damage": 35, "count": 5, "pierce": 10, "cooldown": 0.8, "area": 1.5},
		],
	},
	"flamethrower": {
		"name": "喷火器",
		"description": "近距离火焰喷射",
		"icon": "res://assets/images/weapons/fire.png",
		"projectile_scene": "flame",
		"base_damage": 8,
		"cooldown": 0.15,
		"projectile_speed": 300.0,
		"projectile_count": 1,
		"projectile_pierce": 2,
		"area_size": 1.0,
		"duration": 0.5,
		"knockback": 20.0,
		"max_level": 8,
		"levels": [
			{"damage": 8, "count": 1, "pierce": 2, "cooldown": 0.15, "area": 1.0},
			{"damage": 10, "count": 1, "pierce": 3, "cooldown": 0.14, "area": 1.1},
			{"damage": 12, "count": 2, "pierce": 3, "cooldown": 0.13, "area": 1.2},
			{"damage": 14, "count": 2, "pierce": 4, "cooldown": 0.12, "area": 1.3},
			{"damage": 16, "count": 3, "pierce": 4, "cooldown": 0.11, "area": 1.4},
			{"damage": 18, "count": 3, "pierce": 5, "cooldown": 0.10, "area": 1.5},
			{"damage": 20, "count": 4, "pierce": 6, "cooldown": 0.09, "area": 1.6},
			{"damage": 25, "count": 5, "pierce": 8, "cooldown": 0.08, "area": 2.0},
		],
	},
	"drone": {
		"name": "无人机",
		"description": "自动追踪敌人的无人机",
		"icon": "res://assets/images/weapons/drone.png",
		"projectile_scene": "homing",
		"base_damage": 15,
		"cooldown": 1.0,
		"projectile_speed": 250.0,
		"projectile_count": 1,
		"projectile_pierce": 1,
		"area_size": 1.0,
		"duration": 5.0,
		"knockback": 30.0,
		"max_level": 8,
		"levels": [
			{"damage": 15, "count": 1, "pierce": 1, "cooldown": 1.0, "area": 1.0},
			{"damage": 18, "count": 1, "pierce": 1, "cooldown": 0.9, "area": 1.0},
			{"damage": 21, "count": 2, "pierce": 1, "cooldown": 0.9, "area": 1.0},
			{"damage": 24, "count": 2, "pierce": 2, "cooldown": 0.8, "area": 1.1},
			{"damage": 27, "count": 3, "pierce": 2, "cooldown": 0.8, "area": 1.1},
			{"damage": 30, "count": 3, "pierce": 3, "cooldown": 0.7, "area": 1.2},
			{"damage": 35, "count": 4, "pierce": 3, "cooldown": 0.7, "area": 1.2},
			{"damage": 40, "count": 5, "pierce": 5, "cooldown": 0.5, "area": 1.5},
		],
	},
	"missile": {
		"name": "导弹",
		"description": "追踪导弹，大范围爆炸",
		"icon": "res://assets/images/weapons/missile.png",
		"projectile_scene": "missile",
		"base_damage": 35,
		"cooldown": 3.0,
		"projectile_speed": 200.0,
		"projectile_count": 1,
		"projectile_pierce": 0,
		"area_size": 2.0,
		"duration": 0.0,
		"knockback": 200.0,
		"max_level": 8,
		"levels": [
			{"damage": 35, "count": 1, "pierce": 0, "cooldown": 3.0, "area": 2.0},
			{"damage": 45, "count": 1, "pierce": 0, "cooldown": 2.8, "area": 2.2},
			{"damage": 55, "count": 2, "pierce": 0, "cooldown": 2.6, "area": 2.4},
			{"damage": 65, "count": 2, "pierce": 0, "cooldown": 2.4, "area": 2.6},
			{"damage": 75, "count": 2, "pierce": 0, "cooldown": 2.2, "area": 2.8},
			{"damage": 85, "count": 3, "pierce": 0, "cooldown": 2.0, "area": 3.0},
			{"damage": 100, "count": 3, "pierce": 0, "cooldown": 1.8, "area": 3.2},
			{"damage": 120, "count": 4, "pierce": 0, "cooldown": 1.5, "area": 4.0},
		],
	},
	"talisman": {
		"name": "符咒",
		"description": "环绕护盾",
		"icon": "res://assets/images/weapons/talisman.png",
		"projectile_scene": "orbiting",
		"base_damage": 12,
		"cooldown": 2.0,
		"projectile_speed": 150.0,
		"projectile_count": 2,
		"projectile_pierce": 999,
		"area_size": 1.0,
		"duration": 5.0,
		"knockback": 40.0,
		"max_level": 8,
		"levels": [
			{"damage": 12, "count": 2, "pierce": 999, "cooldown": 2.0, "area": 1.0},
			{"damage": 15, "count": 3, "pierce": 999, "cooldown": 2.0, "area": 1.0},
			{"damage": 18, "count": 3, "pierce": 999, "cooldown": 1.8, "area": 1.1},
			{"damage": 21, "count": 4, "pierce": 999, "cooldown": 1.8, "area": 1.1},
			{"damage": 24, "count": 4, "pierce": 999, "cooldown": 1.6, "area": 1.2},
			{"damage": 27, "count": 5, "pierce": 999, "cooldown": 1.6, "area": 1.2},
			{"damage": 30, "count": 6, "pierce": 999, "cooldown": 1.4, "area": 1.3},
			{"damage": 35, "count": 8, "pierce": 999, "cooldown": 1.0, "area": 1.5},
		],
	},
	"dagger": {
		"name": "飞刀",
		"description": "快速投掷飞刀",
		"icon": "res://assets/images/weapons/dagger.png",
		"projectile_scene": "bullet",
		"base_damage": 8,
		"cooldown": 0.5,
		"projectile_speed": 600.0,
		"projectile_count": 1,
		"projectile_pierce": 1,
		"area_size": 0.8,
		"duration": 0.0,
		"knockback": 30.0,
		"max_level": 8,
		"levels": [
			{"damage": 8, "count": 1, "pierce": 1, "cooldown": 0.5, "area": 0.8},
			{"damage": 10, "count": 2, "pierce": 1, "cooldown": 0.5, "area": 0.8},
			{"damage": 12, "count": 2, "pierce": 2, "cooldown": 0.45, "area": 0.9},
			{"damage": 14, "count": 3, "pierce": 2, "cooldown": 0.45, "area": 0.9},
			{"damage": 16, "count": 3, "pierce": 3, "cooldown": 0.4, "area": 1.0},
			{"damage": 18, "count": 4, "pierce": 3, "cooldown": 0.4, "area": 1.0},
			{"damage": 20, "count": 5, "pierce": 4, "cooldown": 0.35, "area": 1.1},
			{"damage": 25, "count": 6, "pierce": 5, "cooldown": 0.3, "area": 1.2},
		],
	},
	"orbital": {
		"name": "轨道炮",
		"description": "穿透射线",
		"icon": "res://assets/images/weapons/orbital.png",
		"projectile_scene": "beam",
		"base_damage": 20,
		"cooldown": 2.0,
		"projectile_speed": 0.0,
		"projectile_count": 1,
		"projectile_pierce": 999,
		"area_size": 1.5,
		"duration": 1.0,
		"knockback": 0.0,
		"max_level": 8,
		"levels": [
			{"damage": 20, "count": 1, "pierce": 999, "cooldown": 2.0, "area": 1.5},
			{"damage": 25, "count": 1, "pierce": 999, "cooldown": 1.8, "area": 1.7},
			{"damage": 30, "count": 2, "pierce": 999, "cooldown": 1.8, "area": 1.9},
			{"damage": 35, "count": 2, "pierce": 999, "cooldown": 1.6, "area": 2.1},
			{"damage": 40, "count": 3, "pierce": 999, "cooldown": 1.6, "area": 2.3},
			{"damage": 45, "count": 3, "pierce": 999, "cooldown": 1.4, "area": 2.5},
			{"damage": 50, "count": 4, "pierce": 999, "cooldown": 1.2, "area": 2.7},
			{"damage": 60, "count": 5, "pierce": 999, "cooldown": 1.0, "area": 3.0},
		],
	},
	"pulse": {
		"name": "脉冲",
		"description": "周围脉冲波",
		"icon": "res://assets/images/weapons/pulse.png",
		"projectile_scene": "pulse",
		"base_damage": 15,
		"cooldown": 1.5,
		"projectile_speed": 0.0,
		"projectile_count": 1,
		"projectile_pierce": 999,
		"area_size": 2.0,
		"duration": 0.3,
		"knockback": 100.0,
		"max_level": 8,
		"levels": [
			{"damage": 15, "count": 1, "pierce": 999, "cooldown": 1.5, "area": 2.0},
			{"damage": 18, "count": 1, "pierce": 999, "cooldown": 1.4, "area": 2.2},
			{"damage": 21, "count": 1, "pierce": 999, "cooldown": 1.3, "area": 2.4},
			{"damage": 24, "count": 1, "pierce": 999, "cooldown": 1.2, "area": 2.6},
			{"damage": 27, "count": 1, "pierce": 999, "cooldown": 1.1, "area": 2.8},
			{"damage": 30, "count": 1, "pierce": 999, "cooldown": 1.0, "area": 3.0},
			{"damage": 35, "count": 1, "pierce": 999, "cooldown": 0.9, "area": 3.5},
			{"damage": 40, "count": 1, "pierce": 999, "cooldown": 0.7, "area": 4.0},
		],
	},
	"matrix": {
		"name": "矩阵",
		"description": "随机位置爆炸",
		"icon": "res://assets/images/weapons/matrix.png",
		"projectile_scene": "explosive",
		"base_damage": 18,
		"cooldown": 1.0,
		"projectile_speed": 0.0,
		"projectile_count": 1,
		"projectile_pierce": 0,
		"area_size": 1.5,
		"duration": 0.0,
		"knockback": 80.0,
		"max_level": 8,
		"levels": [
			{"damage": 18, "count": 1, "pierce": 0, "cooldown": 1.0, "area": 1.5},
			{"damage": 22, "count": 2, "pierce": 0, "cooldown": 1.0, "area": 1.5},
			{"damage": 26, "count": 2, "pierce": 0, "cooldown": 0.9, "area": 1.7},
			{"damage": 30, "count": 3, "pierce": 0, "cooldown": 0.9, "area": 1.7},
			{"damage": 34, "count": 3, "pierce": 0, "cooldown": 0.8, "area": 1.9},
			{"damage": 38, "count": 4, "pierce": 0, "cooldown": 0.8, "area": 1.9},
			{"damage": 42, "count": 5, "pierce": 0, "cooldown": 0.7, "area": 2.1},
			{"damage": 50, "count": 6, "pierce": 0, "cooldown": 0.5, "area": 2.5},
		],
	},
	"star": {
		"name": "星星",
		"description": "随机方向星星",
		"icon": "res://assets/images/weapons/star.png",
		"projectile_scene": "bullet",
		"base_damage": 10,
		"cooldown": 0.8,
		"projectile_speed": 400.0,
		"projectile_count": 3,
		"projectile_pierce": 1,
		"area_size": 1.0,
		"duration": 0.0,
		"knockback": 30.0,
		"max_level": 8,
		"levels": [
			{"damage": 10, "count": 3, "pierce": 1, "cooldown": 0.8, "area": 1.0},
			{"damage": 12, "count": 4, "pierce": 1, "cooldown": 0.8, "area": 1.0},
			{"damage": 14, "count": 4, "pierce": 2, "cooldown": 0.7, "area": 1.1},
			{"damage": 16, "count": 5, "pierce": 2, "cooldown": 0.7, "area": 1.1},
			{"damage": 18, "count": 5, "pierce": 3, "cooldown": 0.6, "area": 1.2},
			{"damage": 20, "count": 6, "pierce": 3, "cooldown": 0.6, "area": 1.2},
			{"damage": 22, "count": 7, "pierce": 4, "cooldown": 0.5, "area": 1.3},
			{"damage": 25, "count": 10, "pierce": 5, "cooldown": 0.4, "area": 1.5},
		],
	},
	"holywater": {
		"name": "圣水",
		"description": "地面持续伤害区域",
		"icon": "res://assets/images/weapons/holywater.png",
		"projectile_scene": "puddle",
		"base_damage": 10,
		"cooldown": 3.0,
		"projectile_speed": 200.0,
		"projectile_count": 1,
		"projectile_pierce": 999,
		"area_size": 1.5,
		"duration": 4.0,
		"knockback": 0.0,
		"max_level": 8,
		"levels": [
			{"damage": 10, "count": 1, "pierce": 999, "cooldown": 3.0, "area": 1.5},
			{"damage": 13, "count": 1, "pierce": 999, "cooldown": 2.8, "area": 1.7},
			{"damage": 16, "count": 2, "pierce": 999, "cooldown": 2.6, "area": 1.9},
			{"damage": 19, "count": 2, "pierce": 999, "cooldown": 2.4, "area": 2.1},
			{"damage": 22, "count": 2, "pierce": 999, "cooldown": 2.2, "area": 2.3},
			{"damage": 25, "count": 3, "pierce": 999, "cooldown": 2.0, "area": 2.5},
			{"damage": 28, "count": 3, "pierce": 999, "cooldown": 1.8, "area": 2.7},
			{"damage": 35, "count": 4, "pierce": 999, "cooldown": 1.5, "area": 3.0},
		],
	},
	"fireroad": {
		"name": "火焰路径",
		"description": "移动时留下火焰",
		"icon": "res://assets/images/weapons/fireroad.png",
		"projectile_scene": "fireroad",
		"base_damage": 8,
		"cooldown": 0.3,
		"projectile_speed": 0.0,
		"projectile_count": 1,
		"projectile_pierce": 999,
		"area_size": 1.0,
		"duration": 2.0,
		"knockback": 10.0,
		"max_level": 8,
		"levels": [
			{"damage": 8, "count": 1, "pierce": 999, "cooldown": 0.3, "area": 1.0},
			{"damage": 10, "count": 1, "pierce": 999, "cooldown": 0.28, "area": 1.1},
			{"damage": 12, "count": 1, "pierce": 999, "cooldown": 0.26, "area": 1.2},
			{"damage": 14, "count": 1, "pierce": 999, "cooldown": 0.24, "area": 1.3},
			{"damage": 16, "count": 1, "pierce": 999, "cooldown": 0.22, "area": 1.4},
			{"damage": 18, "count": 1, "pierce": 999, "cooldown": 0.20, "area": 1.5},
			{"damage": 20, "count": 1, "pierce": 999, "cooldown": 0.18, "area": 1.7},
			{"damage": 25, "count": 1, "pierce": 999, "cooldown": 0.15, "area": 2.0},
		],
	},
}

# ============================================================
# PASSIVE ITEM DATA
# ============================================================
var passive_items := {
	"armor": {
		"name": "护甲",
		"description": "减少受到的伤害",
		"icon": "res://assets/images/items/passive_armor.png",
		"max_level": 5,
		"stat": "armor",
		"values": [1, 2, 3, 4, 5],
	},
	"damage": {
		"name": "力量",
		"description": "增加伤害",
		"icon": "res://assets/images/items/passive_damage.png",
		"max_level": 5,
		"stat": "damage_mult",
		"values": [1.1, 1.2, 1.3, 1.4, 1.5],
	},
	"speed": {
		"name": "弹速",
		"description": "增加弹射物速度",
		"icon": "res://assets/images/items/passive_speed.png",
		"max_level": 5,
		"stat": "projectile_speed",
		"values": [1.1, 1.2, 1.3, 1.4, 1.5],
	},
	"cooldown": {
		"name": "冷却缩减",
		"description": "减少武器冷却时间",
		"icon": "res://assets/images/items/passive_cooldown.png",
		"max_level": 5,
		"stat": "cooldown_mult",
		"values": [0.95, 0.90, 0.85, 0.80, 0.75],
	},
	"critical": {
		"name": "暴击",
		"description": "增加暴击率",
		"icon": "res://assets/images/items/passive_critical.png",
		"max_level": 5,
		"stat": "crit_chance",
		"values": [0.05, 0.10, 0.15, 0.20, 0.25],
	},
	"magnet": {
		"name": "磁铁",
		"description": "增加拾取范围",
		"icon": "res://assets/images/items/passive_magnet.png",
		"max_level": 5,
		"stat": "magnet_range",
		"values": [75, 100, 130, 165, 200],
	},
	"maxhp": {
		"name": "生命上限",
		"description": "增加最大生命值",
		"icon": "res://assets/images/items/passive_maxhp.png",
		"max_level": 5,
		"stat": "max_hp_mult",
		"values": [1.1, 1.2, 1.3, 1.4, 1.5],
	},
	"recovery": {
		"name": "恢复",
		"description": "每秒恢复生命",
		"icon": "res://assets/images/items/passive_recovery.png",
		"max_level": 5,
		"stat": "hp_regen",
		"values": [0.2, 0.4, 0.6, 0.8, 1.0],
	},
	"luck": {
		"name": "幸运",
		"description": "增加幸运值",
		"icon": "res://assets/images/items/passive_luck.png",
		"max_level": 5,
		"stat": "luck",
		"values": [1.1, 1.2, 1.3, 1.4, 1.5],
	},
	"movespeed": {
		"name": "移速",
		"description": "增加移动速度",
		"icon": "res://assets/images/items/passive_movespeed.png",
		"max_level": 5,
		"stat": "speed_mult",
		"values": [1.1, 1.15, 1.2, 1.25, 1.3],
	},
	"growth": {
		"name": "成长",
		"description": "增加经验获取",
		"icon": "res://assets/images/items/passive_growth.png",
		"max_level": 5,
		"stat": "growth",
		"values": [1.1, 1.2, 1.3, 1.4, 1.5],
	},
	"greed": {
		"name": "贪婪",
		"description": "增加金币获取",
		"icon": "res://assets/images/items/passive_greed.png",
		"max_level": 5,
		"stat": "greed",
		"values": [1.2, 1.4, 1.6, 1.8, 2.0],
	},
	"duration": {
		"name": "持续时间",
		"description": "增加效果持续时间",
		"icon": "res://assets/images/items/passive_duration.png",
		"max_level": 5,
		"stat": "duration_mult",
		"values": [1.1, 1.2, 1.3, 1.4, 1.5],
	},
	"area": {
		"name": "范围",
		"description": "增加攻击范围",
		"icon": "res://assets/images/items/passive_area.png",
		"max_level": 5,
		"stat": "area_mult",
		"values": [1.1, 1.2, 1.3, 1.4, 1.5],
	},
	"amount": {
		"name": "数量",
		"description": "增加弹射物数量",
		"icon": "res://assets/images/items/passive_amount.png",
		"max_level": 3,
		"stat": "amount_bonus",
		"values": [1, 2, 3],
	},
	"revival": {
		"name": "复活",
		"description": "死亡时复活",
		"icon": "res://assets/images/items/passive_revival.png",
		"max_level": 3,
		"stat": "revival_count",
		"values": [1, 2, 3],
	},
}

# ============================================================
# ENEMY DATA
# ============================================================
var enemies := {
	"brainless_basic": {
		"name": "无脑者",
		"sprite": "res://assets/images/enemies/brainless_basic.png",
		"max_hp": 10,
		"damage": 5,
		"speed": 80.0,
		"exp": 1,
		"armor": 0,
		"color": Color(0.4, 0.4, 0.4),
		"coin_min": 1,
		"coin_max": 3,
	},
	"brainless_fast": {
		"name": "快速无脑者",
		"sprite": "res://assets/images/enemies/brainless_fast.png",
		"max_hp": 8,
		"damage": 5,
		"speed": 150.0,
		"exp": 2,
		"armor": 0,
		"color": Color(0.6, 0.3, 0.3),
		"coin_min": 2,
		"coin_max": 4,
	},
	"brainless_tank": {
		"name": "重装无脑者",
		"sprite": "res://assets/images/enemies/brainless_tank.png",
		"max_hp": 40,
		"damage": 10,
		"speed": 50.0,
		"exp": 5,
		"armor": 2,
		"color": Color(0.3, 0.3, 0.5),
		"coin_min": 4,
		"coin_max": 8,
	},
	"brainless_ranged": {
		"name": "远程无脑者",
		"sprite": "res://assets/images/enemies/brainless_ranged.png",
		"max_hp": 12,
		"damage": 8,
		"speed": 60.0,
		"exp": 3,
		"armor": 0,
		"color": Color(0.5, 0.4, 0.3),
		"coin_min": 3,
		"coin_max": 6,
	},
}

# ============================================================
# BOSS DATA
# ============================================================
var bosses := {
	"butcher": {
		"name": "血腥屠夫",
		"sprite": "res://assets/images/bosses/boss_butcher.png",
		"max_hp": 300,
		"damage": 10,
		"speed": 80.0,
		"exp": 30,
		"armor": 2,
		"color": Color(0.8, 0.2, 0.2),
		"phases": 1,
		"coin_min": 30,
		"coin_max": 50,
	},
	"sakura": {
		"name": "樱",
		"sprite": "res://assets/images/bosses/boss_sakura.png",
		"max_hp": 500,
		"damage": 15,
		"speed": 100.0,
		"exp": 50,
		"armor": 3,
		"color": Color(1.0, 0.3, 0.3),
		"phases": 2,
		"coin_min": 50,
		"coin_max": 80,
	},
	"miho": {
		"name": "美穗 - 暴走形态",
		"sprite": "res://assets/images/bosses/boss_miho.png",
		"max_hp": 800,
		"damage": 20,
		"speed": 90.0,
		"exp": 80,
		"armor": 5,
		"color": Color(1.0, 0.7, 0.3),
		"phases": 2,
		"coin_min": 80,
		"coin_max": 120,
	},
	"kanna": {
		"name": "栞那 - 暴走形态",
		"sprite": "res://assets/images/bosses/boss_kanna.png",
		"max_hp": 1200,
		"damage": 25,
		"speed": 110.0,
		"exp": 120,
		"armor": 4,
		"color": Color(0.6, 0.3, 0.8),
		"phases": 3,
		"coin_min": 120,
		"coin_max": 180,
	},
	"kiko": {
		"name": "绮子 - 暴走形态",
		"sprite": "res://assets/images/bosses/boss_kiko.png",
		"max_hp": 1500,
		"damage": 30,
		"speed": 100.0,
		"exp": 150,
		"armor": 6,
		"color": Color(0.7, 0.5, 0.9),
		"phases": 3,
		"coin_min": 150,
		"coin_max": 220,
	},
	"kureha": {
		"name": "暮叶 - 暴走形态",
		"sprite": "res://assets/images/bosses/boss_kureha.png",
		"max_hp": 2000,
		"damage": 35,
		"speed": 120.0,
		"exp": 200,
		"armor": 8,
		"color": Color(0.3, 0.8, 0.5),
		"phases": 3,
		"coin_min": 200,
		"coin_max": 300,
	},
}

# ============================================================
# MAP DATA
# ============================================================
var maps := {
	"tutorial": {
		"name": "废弃城市",
		"description": "新手教学关卡，熟悉操作与战斗。默认解锁，通关后可解锁下一关卡。",
		"tile": "res://assets/images/maps/tile_stone.png",
		"bg_color": Color(0.25, 0.25, 0.28),
		"size": Vector2(3000, 3000),
		"enemy_types": ["brainless_basic"],
		"boss": "butcher",
		"spawn_rate_base": 3.5,
		"spawn_rate_increase": 0.0,
		"max_enemies": 50,
		"time_limit": 180,
		"normal_phase_duration": 180.0,
		"exp_mult": 3.0,
		"unlock_condition": "默认解锁",
		"unlock_prerequisite": "",
		"is_tutorial": true,
	},
	"endless_road": {
		"name": "公路",
		"description": "第一章主线关卡。生存5分钟后迎战Boss樱！通关后解锁角色「樱」。通关「废弃城市」后解锁。",
		"tile": "res://assets/images/maps/tile_grass.png",
		"bg_color": Color(0.31, 0.47, 0.24),
		"size": Vector2(4000, 4000),
		"enemy_types": ["brainless_basic", "brainless_fast"],
		"boss": "sakura",
		"spawn_rate_base": 1.0,
		"spawn_rate_increase": 0.01,
		"max_enemies": 200,
		"time_limit": 900,
		"unlock_condition": "通关「废弃城市」后解锁",
		"unlock_prerequisite": "tutorial",
	},
	"wasteland": {
		"name": "荒原",
		"description": "第一章支线关卡。荒凉的沙漠中危机四伏，敌人更强更多。通关「公路」后解锁。",
		"tile": "res://assets/images/maps/tile_sand.png",
		"bg_color": Color(0.71, 0.63, 0.39),
		"size": Vector2(5000, 5000),
		"enemy_types": ["brainless_basic", "brainless_fast", "brainless_tank"],
		"boss": "miho",
		"spawn_rate_base": 0.8,
		"spawn_rate_increase": 0.015,
		"max_enemies": 300,
		"time_limit": 900,
		"unlock_condition": "通关「公路」后解锁",
		"unlock_prerequisite": "endless_road",
	},
	"crimson_forest": {
		"name": "森林",
		"description": "第一章终极关卡。被鲜血染红的森林深处，大量强敌潜伏。通关「荒原」后解锁。",
		"tile": "res://assets/images/maps/tile_forest.png",
		"bg_color": Color(0.16, 0.31, 0.12),
		"size": Vector2(6000, 6000),
		"enemy_types": ["brainless_basic", "brainless_fast", "brainless_tank", "brainless_ranged"],
		"boss": "kanna",
		"spawn_rate_base": 0.6,
		"spawn_rate_increase": 0.02,
		"max_enemies": 400,
		"time_limit": 900,
		"unlock_condition": "通关「荒原」后解锁",
		"unlock_prerequisite": "wasteland",
	},
}

# ============================================================
# STORY / DIALOGUE DATA
# ============================================================
var story_dialogues := {
	"tutorial_intro": [
		{"speaker": "系统", "text": "欢迎来到废弃城市——新手训练场。"},
		{"speaker": "系统", "text": "使用 WASD 或方向键移动角色。"},
		{"speaker": "系统", "text": "武器会自动攻击靠近的敌人。"},
		{"speaker": "系统", "text": "击杀敌人获取经验，升级后可选择新武器或道具。"},
		{"speaker": "系统", "text": "存活3分钟后将迎来Boss战，击败Boss即可通关！"},
		{"speaker": "系统", "text": "准备好了吗？祝你好运！"},
	],
	"intro": [
		{"speaker": "系统", "text": "欢迎来到异世界前线！"},
		{"speaker": "系统", "text": "在这个世界中，你需要生存下去。"},
		{"speaker": "系统", "text": "使用WASD移动，武器会自动攻击。"},
		{"speaker": "系统", "text": "击杀敌人获取经验，升级后选择新武器或道具。"},
		{"speaker": "系统", "text": "祝你好运！"},
	],
	"boss_butcher": [
		{"speaker": "血腥屠夫", "text": "嘎嘎嘎...新鲜的肉..."},
		{"speaker": "血腥屠夫", "text": "让我来给你上一课吧！"},
	],
	"boss_sakura": [
		{"speaker": "???", "text": "你终于来了..."},
		{"speaker": "樱", "text": "我不会让你通过这里的！"},
	],
	"boss_miho": [
		{"speaker": "美穗", "text": "这片荒原是我的领地。"},
		{"speaker": "美穗", "text": "准备好受死了吗？"},
	],
	"boss_kanna": [
		{"speaker": "栞那", "text": "森林深处的力量...你无法理解。"},
		{"speaker": "栞那", "text": "让我来终结你吧！"},
	],
	"victory": [
		{"speaker": "系统", "text": "恭喜你！你成功生存了下来！"},
		{"speaker": "系统", "text": "你是最强的幸存者！"},
	],
}

# ============================================================
# CHARACTER LEVEL SYSTEM
# ============================================================
const CHARACTER_MAX_LEVEL: int = 10
const CHARACTER_LEVEL_BASE_COST: int = 50

# Per-level stat bonuses
const LEVEL_BONUSES := {
	"max_hp": 5,
	"speed": 5.0,
	"armor": 0.2,
	"damage_mult": 0.05,
	"cooldown_mult": -0.01,
	"crit_chance": 0.01,
	"crit_damage": 0.05,
	"luck": 0.05,
	"growth": 0.05,
	"greed": 0.05,
	"magnet_range": 3.0,
}

func get_character_level_up_cost(level: int) -> int:
	return CHARACTER_LEVEL_BASE_COST * (level + 1)

func get_character_stats_at_level(char_id: String, level: int) -> Dictionary:
	if not characters.has(char_id):
		return {}
	var base = characters[char_id]
	var lvl = clampi(level, 1, CHARACTER_MAX_LEVEL)
	var bonus = lvl - 1
	var result := {}
	for key in base:
		result[key] = base[key]
	if bonus > 0:
		for stat in LEVEL_BONUSES:
			if result.has(stat):
				result[stat] = result[stat] + LEVEL_BONUSES[stat] * bonus
	return result

# ============================================================
# LEVEL UP TABLE
# ============================================================
var exp_table: Array[int] = []

func _ready():
	_build_exp_table()

func _build_exp_table():
	exp_table.clear()
	for i in range(200):
		var exp_needed: int = int(10 + i * 5 + pow(i, 1.5) * 2)
		exp_table.append(exp_needed)

func get_exp_for_level(level: int) -> int:
	if level < exp_table.size():
		return exp_table[level]
	return exp_table[exp_table.size() - 1] + (level - exp_table.size() + 1) * 100

func get_weapon_data(weapon_id: String, level: int) -> Dictionary:
	if not weapons.has(weapon_id):
		return {}
	var w = weapons[weapon_id]
	var lvl = clampi(level, 0, w["levels"].size() - 1)
	return w["levels"][lvl]

func get_character_list() -> Array:
	var result := []
	for id in characters:
		var c = characters[id].duplicate()
		c["id"] = id
		result.append(c)
	return result

func get_weapon_list() -> Array:
	var result := []
	for id in weapons:
		var w = weapons[id].duplicate()
		w["id"] = id
		result.append(w)
	return result

func get_passive_list() -> Array:
	var result := []
	for id in passive_items:
		var p = passive_items[id].duplicate()
		p["id"] = id
		result.append(p)
	return result